"""init

Revision ID: aa0fbc81f302
Revises: 
Create Date: 2024-02-29 01:07:38.821672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'aa0fbc81f302'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processes', sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('processes', sa.Column('customer_surname', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processes', 'customer_surname')
    op.drop_column('processes', 'customer_name')
    # ### end Alembic commands ###
